<?php

/**
 * Horde Routes package
 *
 * @author  Ralf Lang <ralf.lang@ralf-lang.de>
 * @license http://www.horde.org/licenses/bsd BSD
 * @package Routes
 */

namespace Horde\Routes\Test;

use PHPUnit\Framework\TestCase;
use Horde\Routes\Mapper;
use Horde\Routes\RouteBuilder;
use InvalidArgumentException;

/**
 * Tests for multi-path route feature with auto-naming
 *
 * @package Routes
 * @coversNothing
 */
class MultiPathRouteTest extends TestCase
{
    /**
     * Test withSecondaryRoute() in builder
     */
    public function testWithSecondaryRoute(): void
    {
        $m = new Mapper();

        $m->route('/responsive')
            ->withName('ResponsiveRules')
            ->withController('ResponsiveController')
            ->noMiddleware()
            ->withSecondaryRoute('/smartmobile')
            ->withSecondaryRoute('/smartmobile.php')
            ->add();

        // All paths should match
        $this->assertNotNull($m->match('/responsive'));
        $this->assertNotNull($m->match('/smartmobile'));
        $this->assertNotNull($m->match('/smartmobile.php'));

        // All should have same controller
        $result1 = $m->match('/responsive');
        $result2 = $m->match('/smartmobile');
        $result3 = $m->match('/smartmobile.php');

        $this->assertEquals('ResponsiveController', $result1['controller']);
        $this->assertEquals('ResponsiveController', $result2['controller']);
        $this->assertEquals('ResponsiveController', $result3['controller']);

        // Only primary generates
        $url = $m->generate(['controller' => 'ResponsiveController']);
        $this->assertEquals('/responsive', $url);
    }

    /**
     * Test addSecondary() method
     */
    public function testAddSecondary(): void
    {
        $m = new Mapper();

        // Primary route
        $m->route('/responsive')
            ->withName('ResponsiveRules')
            ->withController('ResponsiveController')
            ->noMiddleware()
            ->add();

        // Add secondary routes
        $m->addSecondary('/smartmobile', 'ResponsiveRules');
        $m->addSecondary('/smartmobile.php', 'ResponsiveRules');

        // All paths should match with same controller
        $this->assertEquals(
            'ResponsiveController',
            $m->match('/responsive')['controller']
        );
        $this->assertEquals(
            'ResponsiveController',
            $m->match('/smartmobile')['controller']
        );
        $this->assertEquals(
            'ResponsiveController',
            $m->match('/smartmobile.php')['controller']
        );

        // Only primary generates
        $url = $m->generate(['controller' => 'ResponsiveController']);
        $this->assertEquals('/responsive', $url);
    }

    /**
     * Test auto-generated route names from path
     */
    public function testAutoGeneratedRouteNames(): void
    {
        $m = new Mapper();

        // Simple path
        $m->route('/users/:id')
            ->withController('User')
            ->withAction('show')
            ->add();

        // Multi-segment path
        $m->route('/api/v2/posts/:slug')
            ->withController('Post')
            ->withAction('show')
            ->add();

        // Root path
        $m->route('/')
            ->withController('Home')
            ->add();

        // Check names were generated
        $routes = $m->getRouteList();

        // Find by path
        $usersRoute = array_filter($routes, fn($r) => $r['path'] === '/users/:id');
        $apiRoute = array_filter($routes, fn($r) => $r['path'] === '/api/v2/posts/:slug');
        $rootRoute = array_filter($routes, fn($r) => $r['path'] === '/');

        $this->assertCount(1, $usersRoute);
        $this->assertCount(1, $apiRoute);
        $this->assertCount(1, $rootRoute);

        // Verify auto-generated names (should be CamelCase from path)
        $usersRoute = array_values($usersRoute)[0];
        $apiRoute = array_values($apiRoute)[0];
        $rootRoute = array_values($rootRoute)[0];

        $this->assertEquals('UsersId', $usersRoute['name']);
        $this->assertEquals('ApiV2PostsSlug', $apiRoute['name']);
        $this->assertEquals('Root', $rootRoute['name']);
    }

    /**
     * Test auto-generated names with HTTP verbs
     */
    public function testAutoNamesWithHttpVerbs(): void
    {
        $m = new Mapper();

        // GET /users/:id
        $m->route('/users/:id')
            ->withController('User')
            ->withAction('show')
            ->get()
            ->add();

        // POST /users
        $m->route('/users')
            ->withController('User')
            ->withAction('create')
            ->post()
            ->add();

        // Multiple methods - should not prefix
        $m->route('/api/data')
            ->withController('Api')
            ->methods(['GET', 'POST', 'PUT', 'DELETE'])
            ->add();

        $routes = $m->getRouteList();

        // Find routes
        $getUserRoute = array_filter(
            $routes,
            fn($r)
            => $r['path'] === '/users/:id'
            && isset($r['conditions']['method'])
            && in_array('GET', $r['conditions']['method'])
        );
        $postUserRoute = array_filter(
            $routes,
            fn($r)
            => $r['path'] === '/users'
            && isset($r['conditions']['method'])
            && in_array('POST', $r['conditions']['method'])
        );
        $apiRoute = array_filter($routes, fn($r) => $r['path'] === '/api/data');

        $this->assertCount(1, $getUserRoute);
        $this->assertCount(1, $postUserRoute);
        $this->assertCount(1, $apiRoute);

        $getUserRoute = array_values($getUserRoute)[0];
        $postUserRoute = array_values($postUserRoute)[0];
        $apiRoute = array_values($apiRoute)[0];

        // Verify verb-prefixed names
        $this->assertEquals('GetUsersId', $getUserRoute['name']);
        $this->assertEquals('PostUsers', $postUserRoute['name']);
        // Many methods - no prefix
        $this->assertEquals('ApiData', $apiRoute['name']);
    }

    /**
     * Test that secondary routes don't get named
     */
    public function testSecondaryRoutesNotNamed(): void
    {
        $m = new Mapper();

        $m->route('/responsive')
            ->withName('ResponsiveRules')
            ->withController('ResponsiveController')
            ->withSecondaryRoute('/smartmobile')
            ->add();

        $routes = $m->getRouteList();

        // Primary should be named
        $primaryRoute = array_filter($routes, fn($r) => $r['path'] === '/responsive');
        $this->assertCount(1, $primaryRoute);
        $primaryRoute = array_values($primaryRoute)[0];
        $this->assertEquals('ResponsiveRules', $primaryRoute['name']);
        $this->assertEquals('primary', $primaryRoute['type']);

        // Secondary should not be named
        $secondaryRoute = array_filter($routes, fn($r) => $r['path'] === '/smartmobile');
        $this->assertCount(1, $secondaryRoute);
        $secondaryRoute = array_values($secondaryRoute)[0];
        $this->assertNull($secondaryRoute['name']);
        $this->assertEquals('secondary', $secondaryRoute['type']);
    }

    /**
     * Test that middleware/stack is shared across primary and secondary
     */
    public function testMiddlewareShared(): void
    {
        $m = new Mapper();

        $m->route('/api/users')
            ->withController('User')
            ->withMiddleware(['Auth', 'RateLimit'])
            ->withSecondaryRoute('/legacy/users')
            ->add();

        $primary = $m->match('/api/users');
        $secondary = $m->match('/legacy/users');

        $this->assertEquals(['Auth', 'RateLimit'], $primary['stack']);
        $this->assertEquals(['Auth', 'RateLimit'], $secondary['stack']);
    }

    /**
     * Test addSecondary() with non-existent route throws exception
     */
    public function testAddSecondaryInvalidRoute(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage("named route 'NonExistent' does not exist");

        $m = new Mapper();
        $m->addSecondary('/some-path', 'NonExistent');
    }

    /**
     * Test backward compatibility - routes without secondaries still work
     */
    public function testBackwardCompatibility(): void
    {
        $m = new Mapper();

        // Old array-based connect() should still work
        $m->connect('/old-style', ['controller' => 'OldController']);

        // RouteBuilder without secondaries should work
        $m->route('/new-style')
            ->withController('NewController')
            ->add();

        $this->assertEquals('OldController', $m->match('/old-style')['controller']);
        $this->assertEquals('NewController', $m->match('/new-style')['controller']);
    }

    /**
     * Test auto-naming edge cases - special characters in paths
     */
    public function testAutoNamingSpecialCharacters(): void
    {
        $m = new Mapper();

        // Path with hyphens
        $m->route('/user-profile/:user-id')
            ->withController('User')
            ->add();

        // Path with underscores
        $m->route('/api_endpoint/:resource_id')
            ->withController('Api')
            ->add();

        // Path with dots
        $m->route('/legacy.php/:id')
            ->withController('Legacy')
            ->add();

        // Path with mixed separators
        $m->route('/my-awesome_api.v2/:item-id')
            ->withController('MixedApi')
            ->add();

        $routes = $m->getRouteList();

        // Find routes
        $hyphenRoute = array_values(array_filter($routes, fn($r) => $r['path'] === '/user-profile/:user-id'))[0];
        $underscoreRoute = array_values(array_filter($routes, fn($r) => $r['path'] === '/api_endpoint/:resource_id'))[0];
        $dotRoute = array_values(array_filter($routes, fn($r) => $r['path'] === '/legacy.php/:id'))[0];
        $mixedRoute = array_values(array_filter($routes, fn($r) => $r['path'] === '/my-awesome_api.v2/:item-id'))[0];

        // Verify CamelCase conversion (hyphens, underscores, dots removed)
        $this->assertEquals('UserProfileUserId', $hyphenRoute['name']);
        $this->assertEquals('ApiEndpointResourceId', $underscoreRoute['name']);
        $this->assertEquals('LegacyPhpId', $dotRoute['name']);
        $this->assertEquals('MyAwesomeApiV2ItemId', $mixedRoute['name']);
    }

    /**
     * Test auto-naming with 2-3 HTTP methods
     */
    public function testAutoNamingWithFewMethods(): void
    {
        $m = new Mapper();

        // 2 methods - should have both prefixes
        $m->route('/articles/:id')
            ->withController('Article')
            ->methods(['GET', 'HEAD'])
            ->add();

        // 3 methods - should have all prefixes
        $m->route('/posts/:slug')
            ->withController('Post')
            ->methods(['GET', 'POST', 'PUT'])
            ->add();

        $routes = $m->getRouteList();

        $twoMethodRoute = array_values(array_filter($routes, fn($r) => $r['path'] === '/articles/:id'))[0];
        $threeMethodRoute = array_values(array_filter($routes, fn($r) => $r['path'] === '/posts/:slug'))[0];

        // Verify method prefixes
        $this->assertEquals('GetHeadArticlesId', $twoMethodRoute['name']);
        $this->assertEquals('GetPostPutPostsSlug', $threeMethodRoute['name']);
    }

    /**
     * Test multiple secondary routes with HTTP method restrictions
     */
    public function testMultipleSecondaryRoutesWithHttpMethods(): void
    {
        $m = new Mapper();

        $m->route('/api/v2/users/:id')
            ->withName('ApiUserShow')
            ->withController('ApiUserController')
            ->withAction('show')
            ->withMiddleware(['Auth', 'ApiVersionCheck'])
            ->get()
            ->withSecondaryRoute('/api/user/:id')      // Legacy v1 path
            ->withSecondaryRoute('/users/:id')          // Short path
            ->withSecondaryRoute('/member/:id')         // Alias path
            ->add();

        // Set environment for GET request
        $m->environ = ['REQUEST_METHOD' => 'GET'];

        // All paths should match with same configuration
        $primary = $m->match('/api/v2/users/123');
        $secondary1 = $m->match('/api/user/123');
        $secondary2 = $m->match('/users/123');
        $secondary3 = $m->match('/member/123');

        // Verify all routes return same controller and action
        $this->assertEquals('ApiUserController', $primary['controller']);
        $this->assertEquals('ApiUserController', $secondary1['controller']);
        $this->assertEquals('ApiUserController', $secondary2['controller']);
        $this->assertEquals('ApiUserController', $secondary3['controller']);

        $this->assertEquals('show', $primary['action']);
        $this->assertEquals('show', $secondary1['action']);
        $this->assertEquals('show', $secondary2['action']);
        $this->assertEquals('show', $secondary3['action']);

        // Verify middleware is inherited
        $this->assertEquals(['Auth', 'ApiVersionCheck'], $primary['stack']);
        $this->assertEquals(['Auth', 'ApiVersionCheck'], $secondary1['stack']);
        $this->assertEquals(['Auth', 'ApiVersionCheck'], $secondary2['stack']);
        $this->assertEquals(['Auth', 'ApiVersionCheck'], $secondary3['stack']);

        // Verify ID parameter is captured
        $this->assertEquals('123', $primary['id']);
        $this->assertEquals('123', $secondary1['id']);
        $this->assertEquals('123', $secondary2['id']);
        $this->assertEquals('123', $secondary3['id']);

        // Verify POST request doesn't match (GET only)
        $m->environ = ['REQUEST_METHOD' => 'POST'];
        $this->assertNull($m->match('/api/v2/users/123'));
        $this->assertNull($m->match('/api/user/123'));
        $this->assertNull($m->match('/users/123'));
        $this->assertNull($m->match('/member/123'));

        // Only primary path generates URLs
        $m->environ = ['REQUEST_METHOD' => 'GET'];
        $url = $m->generate(['controller' => 'ApiUserController', 'action' => 'show', 'id' => '456']);
        $this->assertEquals('/api/v2/users/456', $url);
    }
}
