---
id: Routes
name: Routes
full: URL routing/mapping library
description: >-
  A library for mapping URLs into the controllers and actions of an MVC system.
  It is a port of a Python library, Routes, by Ben Bangert
  (http://routes.groovie.org).
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Routes
authors:
  -
    name: Mike Naberezny
    user: mnaberez
    email: mike@maintainable.com
    active: false
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/util: ^3
  optional:
    composer:
      horde/test: ^3
